In [2]:
# 라이브러리 로드
import pandas as pd

In [3]:
# csv 폴더 안에 있는 corona.csv 파일 로드
# 상대 경로 사용
# 현재 경로(./) -> 상위 디렉토리 (../) -> 하위 디렉토리 (csv/) -> 파일 선택(corona.csv)
corona = pd.read_csv(
    "./../csv/corona.csv"
)

In [4]:
# 로그가 된 외부 데이터 파일의 정보를 확인
# 상위 n개의 데이터를 출력
corona.head()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,0,2022-06-08 09:09:05.982,24305,18188200,904,20220608,00:00,NaN,NaN,NaN
1,1,2022-06-07 09:09:00.897,24299,18174842,903,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2,2022-06-06 09:00:06.734,24279,18168670,902,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,3,2022-06-05 08:53:19.426,24258,18163648,901,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,4,2022-06-04 08:56:49.219,24238,18153814,900,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN

In [5]:
# 데이터에서 하위 n개를 출력
corona.tail()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
815,815,2020-03-14 00:00:00.000,72,8086,55,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,816,2020-03-13 00:00:00.000,67,7979,54,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,817,2020-03-12 00:00:00.000,66,7869,53,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,818,2020-03-11 00:00:00.000,60,7755,52,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,819,2020-03-10 00:00:00.000,54,7513,51,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [6]:
corona.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 820 entries, 0 to 819
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  820 non-null    int64
 1   createDt    820 non-null    object
 2   deathCnt    820 non-null    int64
 3   decideCnt   820 non-null    int64
 4   seq         820 non-null    int64
 5   stateDt     820 non-null    int64
 6   stateTime   820 non-null    object
 7   updateDt    817 non-null    object
 8   accExamCnt  692 non-null    float64
 9   accDefRate  623 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 64.2+ KB

In [7]:
# 각 컬럼별로 결측치의 개수가 몇개인가?
# 결측치인가? (isna()) -> 
# 합산 ( sum() -> DataFrame 안에 있는 함수 )
corona.isna().sum()

Unnamed: 0      0
createDt        0
deathCnt        0
decideCnt       0
seq             0
stateDt         0
stateTime       0
updateDt        3
accExamCnt    128
accDefRate    197
dtype: int64

In [8]:
corona.tail()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
815,815,2020-03-14 00:00:00.000,72,8086,55,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,816,2020-03-13 00:00:00.000,67,7979,54,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,817,2020-03-12 00:00:00.000,66,7869,53,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,818,2020-03-11 00:00:00.000,60,7755,52,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,819,2020-03-10 00:00:00.000,54,7513,51,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [9]:
# 특정 칼럼을 제거
# 제거한다(drop)
# drop() -> 특정 행을 제거할것인가? 열을 제거할것인가?
# drop({data}, axis = 0|1) -> data 와 조건이 맞는 행이나 열은 제거한다
# Unamed: 0, seq 칼럼 제거
corona.drop(
    [ 'Unnamed: 0', 'seq'],
    axis=1,
    inplace=True
)

In [10]:
corona

,createDt,deathCnt,decideCnt,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
...,...,...,...,...,...,...,...,...
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [11]:
# 컬럼의 이름을 변경
# DataFrame 안에 함수 rename() 함수 이용
corona.rename(
    columns= {
        'createDt' : '등록일시',
        'deathCnt' : '총사망자',
        'decideCnt' : '총확진자',
        'stateDt' : '기준일',
        'stateTime' : '기준시간',
        'updateDt' : '수정일시',
        'accExamCnt' : '누적의심자',
        'accDefRate' : '누적확진율'
    }
)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
...,...,...,...,...,...,...,...,...
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [12]:
# DataFrame 안에 columns 변수에 데이터를 대입
# 유의할점 : 기존의 컬럼의 개수와 같은 1차원 데이터를 대입
corona.columns = ['등록일시', '총사망자', '총확진자', '기준일',
                  '기준시간', '수정일시', '누적의심자','누적확진율']

In [13]:
corona.columns

Index(['등록일시', '총사망자', '총확진자', '기준일', '기준시간', '수정일시', '누적의심자', '누적확진율'], dtype='object')

In [14]:
corona.head()

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN

In [15]:
# 데이터프레임에서 정렬을 변경하는 방법 
# 정렬 ( sort ) -> list에서는 사용 가능
# 정렬 기준이 2개 -> index, values
# sort_index(), sort_values() 2개 모두 존재
# sort_values( {col_name}, ascending = {True | False}, inplace = {False | True})
# 등록일시를 기준으로 현재는 내림차순 정렬을 오름차순 정렬로 변경
corona.sort_values(
    ['등록일시'], inplace=True
)

In [16]:
corona

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
...,...,...,...,...,...,...,...,...
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [17]:
corona

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
...,...,...,...,...,...,...,...,...
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [18]:
# 컬럼의 순서를 오름차순 변경
# sort() 함수 존재 x
# columns 데이터를 리스트변경 -> sort()로 데이터를 변경
# -> 필터를 이용해서 컬럼의 순서를 변경
col_list = list(corona.columns)
col_list.sort()

In [19]:
col_list

['기준시간', '기준일', '누적의심자', '누적확진율', '등록일시', '수정일시', '총사망자', '총확진자']

In [20]:
# 복사본을 생성 : backup -> 1차 작업이 완료하고 중간저장
df = corona.copy()

In [21]:
df

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
...,...,...,...,...,...,...,...,...
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [22]:
# 결측치가 존재하는 컬럼이 3개 -> 수정일시, 누적의심자, 누적확진율
# 결측치가 존재하는 데이터를 확인 (수정일시)
# 수정일시 데이터중 결측치가 존재 유무
# df 데이터프레임에서 특정 컬럼 하나를 선택 -> 
    # 2차원 데이터프레임에서 1차원 시리즈로 변경
# 인덱스의 조건식
flag = df['수정일시'].isna()

In [23]:
# 인덱스의 조건을 이용하여 데이터프레임 필터
# DataFrame.loc[ 인덱스의 조건, 컬럼의 조건 ]
# df.loc[ flag != True]
# 비트 연산자 '~'를 이용해서 1차원 논리값의 부정표현
# df.loc[~flag]
# '-' 연산자를 이용하여 1차원 논리값의 부정 표현
df.loc[-flag]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
819,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308
818,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
817,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
816,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
815,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
...,...,...,...,...,...,...,...,...
5,2022-06-03 09:08:18.729,24229,18141775,20220603,00:00,2022-06-08 09:11:38.938,NaN,NaN
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN

In [24]:
# 누적 확진율 데이터에서 결측지인 데이터만 확인
flag = df['누적확진율'].isna()
df.loc[flag]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
196,2021-11-24 09:08:22.071,3362,425059,20211124,00:00,2021-12-02 09:06:01.826,16939923.0,NaN
195,2021-11-25 09:00:47.897,3401,428996,20211125,00:00,2021-12-02 09:06:12.94,16998733.0,NaN
194,2021-11-26 09:03:03.973,3440,432892,20211126,00:00,2021-12-02 09:06:24.138,17056003.0,NaN
193,2021-11-27 09:32:36.026,3492,436959,20211127,00:00,2021-12-02 09:06:37.327,17115754.0,NaN
192,2021-11-28 08:58:53.394,3548,440884,20211128,00:00,2021-12-02 09:06:50.152,17158535.0,NaN
...,...,...,...,...,...,...,...,...
4,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN
3,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
2,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
1,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
0,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN

In [25]:
# loc[조건] -> 조건뿐 아니라 값으로도 필터 가능
df.loc[198:194]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율
198,2021-11-22 09:07:45.615,3298,418249,20211122,00:00,2021-11-26 09:29:38.144,16816616.0,2.778249
197,2021-11-23 08:59:47.863,3328,420946,20211123,00:00,2021-11-30 09:06:13.348,16878955.0,2.787908
196,2021-11-24 09:08:22.071,3362,425059,20211124,00:00,2021-12-02 09:06:01.826,16939923.0,NaN
195,2021-11-25 09:00:47.897,3401,428996,20211125,00:00,2021-12-02 09:06:12.94,16998733.0,NaN
194,2021-11-26 09:03:03.973,3440,432892,20211126,00:00,2021-12-02 09:06:24.138,17056003.0,NaN

In [26]:
# 인덱스를 초기화
# 초기화(reset) + 위치(index)
# reset_index() -> 인덱스를 재지정하고 기존의 인덱스는 컬럼의 데이터로 변환
#  매개변수 inplace -> 원본의 데이터를 수정할 것인가?
#  매개변수 drop    -> 기존의 인덱스를 제거할 것인가?
df.reset_index(drop = True, inplace=True)

In [27]:
# 기존의 데이터를 이용하여 새로운 데이터를 생성 -> 파생변수
# 기존의 데이터만으로 설명이 불가능하거나 상관 관계가 약한경우
# 새로운 데이터를 생성해서 설명이 가능하고 상관관계를 구할 수 있는경우

# 일일확진자 -> 오늘의 총확진자수 - 어제의 총확진자수
df.loc[1, '총확진자'] - df.loc[0,'총확진자']

np.int64(242)

In [28]:
df.loc[2, '총확진자'] - df.loc[1, '총확진자']
# ...
df.loc[819,'총확진자'] - df.loc[818,'총확진자']

np.int64(13358)

In [29]:
# 반복문을 이용하여 일일확진자수를 리스트로 생성
decide_list = [0]

for i in range(1, len(df)):
    # i -> 1부터 819까지 반복
    decide_cnt = df.loc[i,'총확진자'] - df.loc[i-1,'총확진자']
    decide_list.append(decide_cnt)

decide_list

[0,
 np.int64(242),
 np.int64(114),
 np.int64(110),
 np.int64(107),
 np.int64(76),
 np.int64(74),
 np.int64(84),
 np.int64(93),
 np.int64(152),
 np.int64(87),
 np.int64(147),
 np.int64(98),
 np.int64(64),
 np.int64(76),
 np.int64(100),
 np.int64(104),
 np.int64(91),
 np.int64(146),
 np.int64(105),
 np.int64(78),
 np.int64(125),
 np.int64(101),
 np.int64(89),
 np.int64(86),
 np.int64(94),
 np.int64(81),
 np.int64(47),
 np.int64(47),
 np.int64(53),
 np.int64(39),
 np.int64(27),
 np.int64(30),
 np.int64(32),
 np.int64(25),
 np.int64(27),
 np.int64(27),
 np.int64(22),
 np.int64(22),
 np.int64(18),
 np.int64(8),
 np.int64(13),
 np.int64(9),
 np.int64(11),
 np.int64(8),
 np.int64(6),
 np.int64(10),
 np.int64(10),
 np.int64(10),
 np.int64(14),
 np.int64(9),
 np.int64(4),
 np.int64(9),
 np.int64(6),
 np.int64(13),
 np.int64(8),
 np.int64(3),
 np.int64(2),
 np.int64(4),
 np.int64(12),
 np.int64(18),
 np.int64(34),
 np.int64(35),
 np.int64(27),
 np.int64(26),
 np.int64(56),
 np.int64(19),
 np.int64(13),
 np.int64(15),
 np.int64(13),
 np.int64(32),
 np.int64(12),
 np.int64(20),
 np.int64(23),
 np.int64(25),
 np.int64(16),
 np.int64(19),
 np.int64(40),
 np.int64(79),
 np.int64(58),
 np.int64(39),
 np.int64(27),
 np.int64(35),
 np.int64(38),
 np.int64(49),
 np.int64(39),
 np.int64(39),
 np.int64(51),
 np.int64(57),
 np.int64(37),
 np.int64(38),
 np.int64(50),
 np.int64(45),
 np.int64(56),
 np.int64(48),
 np.int64(34),
 np.int64(37),
 np.int64(34),
 np.int64(43),
 np.int64(59),
 np.int64(49),
 np.int64(67),
 np.int64(48),
 np.int64(17),
 np.int64(46),
 np.int64(51),
 np.int64(28),
 np.int64(39),
 np.int64(51),
 np.int64(62),
 np.int64(42),
 np.int64(42),
 np.int64(51),
 np.int64(54),
 np.int64(61),
 np.int64(63),
 np.int64(61),
 np.int64(48),
 np.int64(44),
 np.int64(62),
 np.int64(50),
 np.int64(45),
 np.int64(35),
 np.int64(44),
 np.int64(62),
 np.int64(33),
 np.int64(39),
 np.int64(61),
 np.int64(60),
 np.int64(39),
 np.int64(34),
 np.int64(26),
 np.int64(45),
 np.int64(63),
 np.int64(59),
 np.int64(41),
 np.int64(113),
 np.int64(58),
 np.int64(25),
 np.int64(28),
 np.int64(48),
 np.int64(18),
 np.int64(36),
 np.int64(31),
 np.int64(30),
 np.int64(23),
 np.int64(34),
 np.int64(33),
 np.int64(43),
 np.int64(20),
 np.int64(43),
 np.int64(36),
 np.int64(28),
 np.int64(34),
 np.int64(54),
 np.int64(56),
 np.int64(103),
 np.int64(166),
 np.int64(279),
 np.int64(197),
 np.int64(246),
 np.int64(297),
 np.int64(288),
 np.int64(324),
 np.int64(332),
 np.int64(396),
 np.int64(266),
 np.int64(280),
 np.int64(320),
 np.int64(441),
 np.int64(371),
 np.int64(323),
 np.int64(299),
 np.int64(248),
 np.int64(235),
 np.int64(267),
 np.int64(195),
 np.int64(198),
 np.int64(168),
 np.int64(167),
 np.int64(119),
 np.int64(136),
 np.int64(156),
 np.int64(155),
 np.int64(176),
 np.int64(136),
 np.int64(121),
 np.int64(109),
 np.int64(106),
 np.int64(113),
 np.int64(153),
 np.int64(126),
 np.int64(110),
 np.int64(82),
 np.int64(70),
 np.int64(61),
 np.int64(110),
 np.int64(125),
 np.int64(114),
 np.int64(61),
 np.int64(95),
 np.int64(50),
 np.int64(38),
 np.int64(113),
 np.int64(77),
 np.int64(63),
 np.int64(75),
 np.int64(64),
 np.int64(73),
 np.int64(75),
 np.int64(114),
 np.int64(69),
 np.int64(54),
 np.int64(72),
 np.int64(58),
 np.int64(98),
 np.int64(91),
 np.int64(84),
 np.int64(110),
 np.int64(47),
 np.int64(73),
 np.int64(91),
 np.int64(76),
 np.int64(58),
 np.int64(89),
 np.int64(121),
 np.int64(155),
 np.int64(77),
 np.int64(61),
 np.int64(119),
 np.int64(88),
 np.int64(103),
 np.int64(125),
 np.int64(113),
 np.int64(127),
 np.int64(124),
 np.int64(97),
 np.int64(75),
 np.int64(117),
 np.int64(125),
 np.int64(145),
 np.int64(89),
 np.int64(143),
 np.int64(126),
 np.int64(100),
 np.int64(145),
 np.int64(143),
 np.int64(191),
 np.int64(205),
 np.int64(208),
 np.int64(222),
 np.int64(230),
 np.int64(285),
 np.int64(325),
 np.int64(348),
 np.int64(386),
 np.int64(330),
 np.int64(271),
 np.int64(349),
 np.int64(382),
 np.int64(581),
 np.int64(555),
 np.int64(503),
 np.int64(450),
 np.int64(438),
 np.int64(451),
 np.int64(511),
 np.int64(540),
 np.int64(628),
 np.int64(577),
 np.int64(631),
 np.int64(615),
 np.int64(587),
 np.int64(670),
 np.int64(680),
 np.int64(689),
 np.int64(950),
 np.int64(1030),
 np.int64(718),
 np.int64(880),
 np.int64(1078),
 np.int64(1014),
 np.int64(1064),
 np.int64(1045),
 np.int64(1096),
 np.int64(924),
 np.int64(866),
 np.int64(1090),
 np.int64(985),
 np.int64(1240),
 np.int64(1131),
 np.int64(970),
 np.int64(806),
 np.int64(1044),
 np.int64(1050),
 np.int64(967),
 np.int64(1027),
 np.int64(820),
 np.int64(657),
 np.int64(1020),
 np.int64(714),
 np.int64(838),
 np.int64(869),
 np.int64(674),
 np.int64(641),
 np.int64(657),
 np.int64(451),
 np.int64(537),
 np.int64(561),
 np.int64(524),
 np.int64(512),
 np.int64(580),
 np.int64(520),
 np.int64(389),
 np.int64(386),
 np.int64(404),
 np.int64(400),
 np.int64(346),
 np.int64(431),
 np.int64(392),
 np.int64(437),
 np.int64(349),
 np.int64(559),
 np.int64(497),
 np.int64(469),
 np.int64(456),
 np.int64(354),
 np.int64(305),
 np.int64(336),
 np.int64(467),
 np.int64(451),
 np.int64(370),
 np.int64(390),
 np.int64(371),
 np.int64(288),
 np.int64(303),
 np.int64(444),
 np.int64(504),
 np.int64(403),
 np.int64(362),
 np.int64(326),
 np.int64(343),
 np.int64(457),
 np.int64(621),
 np.int64(621),
 np.int64(561),
 np.int64(448),
 np.int64(416),
 np.int64(332),
 np.int64(356),
 np.int64(440),
 np.int64(395),
 np.int64(387),
 np.int64(415),
 np.int64(355),
 np.int64(355),
 np.int64(344),
 np.int64(444),
 np.int64(424),
 np.int64(398),
 np.int64(418),
 np.int64(416),
 np.int64(346),
 np.int64(446),
 np.int64(470),
 np.int64(465),
 np.int64(488),
 np.int64(490),
 np.int64(459),
 np.int64(379),
 np.int64(363),
 np.int64(469),
 np.int64(445),
 np.int64(463),
 np.int64(447),
 np.int64(456),
 np.int64(415),
 np.int64(346),
 np.int64(428),
 np.int64(430),
 np.int64(489),
 np.int64(505),
 np.int64(482),
 np.int64(382),
 np.int64(447),
 np.int64(506),
 np.int64(551),
 np.int64(557),
 np.int64(543),
 np.int64(543),
 np.int64(473),
 np.int64(477),
 np.int64(668),
 np.int64(700),
 np.int64(671),
 np.int64(677),
 np.int64(614),
 np.int64(587),
 np.int64(542),
 np.int64(731),
 np.int64(698),
 np.int64(673),
 np.int64(658),
 np.int64(671),
 np.int64(532),
 np.int64(549),
 np.int64(731),
 np.int64(735),
 np.int64(797),
 np.int64(785),
 np.int64(644),
 np.int64(499),
 np.int64(512),
 np.int64(769),
 np.int64(679),
 np.int64(661),
 np.int64(627),
 np.int64(606),
 np.int64(488),
 np.int64(541),
 np.int64(676),
 np.int64(574),
 np.int64(525),
 np.int64(701),
 np.int64(564),
 np.int64(463),
 np.int64(510),
 np.int64(634),
 np.int64(715),
 np.int64(747),
 np.int64(681),
 np.int64(610),
 np.int64(619),
 np.int64(528),
 np.int64(654),
 np.int64(646),
 np.int64(561),
 np.int64(666),
 np.int64(585),
 np.int64(530),
 np.int64(516),
 np.int64(705),
 np.int64(629),
 np.int64(587),
 np.int64(533),
 np.int64(910),
 np.int64(-430),
 np.int64(889),
 np.int64(677),
 np.int64(681),
 np.int64(695),
 np.int64(744),
 np.int64(556),
 np.int64(485),
 np.int64(454),
 np.int64(602),
 np.int64(610),
 np.int64(556),
 np.int64(565),
 np.int64(452),
 np.int64(399),
 np.int64(373),
 np.int64(545),
 np.int64(540),
 np.int64(507),
 np.int64(482),
 np.int64(429),
 np.int64(357),
 np.int64(394),
 np.int64(645),
 np.int64(610),
 np.int64(634),
 np.int64(668),
 np.int64(614),
 np.int64(501),
 np.int64(595),
 np.int64(794),
 np.int64(761),
 np.int64(825),
 np.int64(794),
 np.int64(743),
 np.int64(711),
 np.int64(746),
 np.int64(1211),
 np.int64(1275),
 np.int64(1316),
 np.int64(1378),
 np.int64(1324),
 np.int64(1100),
 np.int64(1150),
 np.int64(1613),
 np.int64(1599),
 np.int64(1535),
 np.int64(1449),
 np.int64(1453),
 np.int64(1251),
 np.int64(1278),
 np.int64(1781),
 np.int64(1841),
 np.int64(1629),
 np.int64(1627),
 np.int64(1487),
 np.int64(1318),
 np.int64(1363),
 np.int64(1895),
 np.int64(1673),
 np.int64(1710),
 np.int64(1538),
 np.int64(1442),
 np.int64(1218),
 np.int64(1200),
 np.int64(1725),
 np.int64(1775),
 np.int64(1704),
 np.int64(1823),
 np.int64(1727),
 np.int64(1491),
 np.int64(1537),
 np.int64(2221),
 np.int64(1987),
 np.int64(1989),
 np.int64(1928),
 np.int64(1816),
 np.int64(1554),
 np.int64(1372),
 np.int64(1803),
 np.int64(2152),
 np.int64(2140),
 np.int64(1787),
 np.int64(1626),
 np.int64(1417),
 np.int64(1507),
 np.int64(2154),
 np.int64(1882),
 np.int64(1837),
 np.int64(1791),
 np.int64(1619),
 np.int64(1485),
 np.int64(1370),
 np.int64(2024),
 np.int64(1960),
 np.int64(1708),
 np.int64(1803),
 np.int64(1490),
 np.int64(1375),
 np.int64(1597),
 np.int64(2047),
 np.int64(2049),
 np.int64(1893),
 np.int64(1864),
 np.int64(1755),
 np.int64(1433),
 np.int64(1508),
 np.int64(2065),
 np.int64(1942),
 np.int64(2008),
 np.int64(2087),
 np.int64(1909),
 np.int64(1604),
 np.int64(1729),
 np.int64(1720),
 np.int64(1715),
 np.int64(2429),
 np.int64(3270),
 np.int64(2768),
 np.int64(2381),
 np.int64(2288),
 np.int64(2881),
 np.int64(2561),
 np.int64(2484),
 np.int64(2247),
 np.int64(2085),
 np.int64(1670),
 np.int64(1574),
 np.int64(2027),
 np.int64(2425),
 np.int64(2171),
 np.int64(1953),
 np.int64(1594),
 np.int64(1297),
 np.int64(1346),
 np.int64(1583),
 np.int64(1939),
 np.int64(1683),
 np.int64(1617),
 np.int64(1420),
 np.int64(1050),
 np.int64(1073),
 np.int64(1571),
 np.int64(1441),
 np.int64(1438),
 np.int64(1508),
 np.int64(1421),
 np.int64(1190),
 np.int64(1272),
 np.int64(1945),
 np.int64(2111),
 np.int64(2121),
 np.int64(2104),
 np.int64(2061),
 np.int64(1685),
 np.int64(1588),
 np.int64(2667),
 np.int64(2482),
 np.int64(2343),
 np.int64(2246),
 np.int64(2225),
 np.int64(1754),
 np.int64(1717),
 np.int64(2425),
 np.int64(2518),
 np.int64(2368),
 np.int64(2324),
 np.int64(2418),
 np.int64(2004),
 np.int64(2122),
 np.int64(3189),
 np.int64(3292),
 np.int64(3033),
 np.int64(3205),
 np.int64(3120),
 np.int64(2827),
 np.int64(2697),
 np.int64(4113),
 np.int64(3937),
 np.int64(3896),
 np.int64(4067),
 np.int64(3925),
 np.int64(3307),
 np.int64(3031),
 np.int64(5122),
 np.int64(5263),
 np.int64(4944),
 np.int64(5352),
 np.int64(5125),
 np.int64(4324),
 np.int64(4953),
 np.int64(7173),
 np.int64(7375),
 np.int64(6748),
 np.int64(6977),
 np.int64(6681),
 np.int64(5816),
 np.int64(5567),
 np.int64(7849),
 np.int64(7619),
 np.int64(7434),
 np.int64(7310),
 np.int64(6233),
 np.int64(5316),
 np.int64(5192),
 np.int64(7452),
 np.int64(6914),
 np.int64(6233),
 np.int64(5840),
 np.int64(5413),
 np.int64(4203),
 np.int64(3864),
 np.int64(5407),
 np.int64(5034),
 np.int64(4873),
 np.int64(4415),
 np.int64(3831),
 np.int64(3125),
 np.int64(3021),
 np.int64(4441),
 np.int64(4122),
 np.int64(3713),
 np.int64(3507),
 np.int64(3371),
 np.int64(3005),
 np.int64(3092),
 np.int64(4383),
 np.int64(4164),
 np.int64(4538),
 np.int64(4419),
 np.int64(4189),
 np.int64(3854),
 np.int64(4062),
 np.int64(5803),
 np.int64(6600),
 np.int64(6766),
 np.int64(7004),
 np.int64(7626),
 np.int64(7511),
 np.int64(8570),
 np.int64(13009),
 np.int64(14514),
 np.int64(16093),
 np.int64(17513),
 np.int64(17522),
 np.int64(17077),
 np.int64(18338),
 np.int64(20268),
 np.int64(22906),
 np.int64(27438),
 np.int64(36345),
 np.int64(38689),
 np.int64(35283),
 np.int64(36717),
 np.int64(49567),
 np.int64(54122),
 np.int64(53903),
 np.int64(54935),
 np.int64(56428),
 np.int64(54617),
 np.int64(57164),
 np.int64(90435),
 np.int64(93132),
 np.int64(109823),
 np.int64(102210),
 np.int64(104814),
 np.int64(95339),
 np.int64(99569),
 np.int64(171442),
 np.int64(170015),
 np.int64(165887),
 np.int64(166182),
 np.int64(163561),
 np.int64(139624),
 np.int64(138990),
 np.int64(219228),
 np.int64(198800),
 np.int64(266850),
 np.int64(254327),
 np.int64(243625),
 np.int64(210709),
 np.int64(202702),
 np.int64(342429),
 np.int64(327538),
 np.int64(282973),
 np.int64(383617),
 np.int64(350182),
 np.int64(309779),
 np.int64(362283),
 np.int64(400593),
 np.int64(621204),
 np.int64(406839),
 np.int64(381413),
 np.int64(334653),
 np.int64(209139),
 np.int64(353828),
 np.int64(490771),
 np.int64(395526),
 np.int64(339451),
 np.int64(335541),
 np.int64(318075),
 np.int64(187182),
 np.int64(347500),
 np.int64(424466),
 np.int64(320683),
 np.int64(280231),
 np.int64(264120),
 np.int64(234265),
 np.int64(127163),
 np.int64(266085),
 np.int64(286247),
 np.int64(224784),
 np.int64(205299),
 np.int64(185525),
 np.int64(164456),
 np.int64(90917),
 np.int64(210715),
 np.int64(195382),
 np.int64(148409),
 np.int64(125800),
 np.int64(107882),
 np.int64(92978),
 np.int64(47730),
 np.int64(118462),
 np.int64(111289),
 np.int64(90843),
 np.int64(81033),
 np.int64(75423),
 np.int64(64704),
 np.int64(34361),
 np.int64(80267),
 np.int64(76764),
 np.int64(57446),
 np.int64(50556),
 np.int64(43244),
 np.int64(37760),
 np.int64(20076),
 np.int64(51106),
 np.int64(49046),
 np.int64(42279),
 np.int64(26678),
 np.int64(39563),
 np.int64(40048),
 np.int64(20588),
 np.int64(49896),
 np.int64(43881),
 np.int64(35882),
 np.int64(32435),
 np.int64(29572),
 np.int64(25425),
 np.int64(13290),
 np.int64(35085),
 np.int64(31333),
 np.int64(28109),
 np.int64(25113),
 np.int64(23450),
 np.int64(19289),
 np.int64(9971),
 np.int64(26331),
 np.int64(23936),
 np.int64(18805),
 np.int64(16572),
 np.int64(14374),
 np.int64(12647),
 np.int64(6135),
 np.int64(17185),
 np.int64(15768),
 np.int64(9891),
 np.int64(12539),
 np.int64(12039),
 np.int64(9834),
 np.int64(5022),
 np.int64(6172),
 np.int64(13358)]

In [30]:
len(decide_list)

820

In [31]:
# df에 새로운 칼럼 '일일확진자' 를 추가하고 데이터는 decide_list 대입
# 이것은 dict에서 key : value 를 추가하는 형태와 같다
df['일일확진자'] = decide_list

In [32]:
df

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일확진자
0,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308,0
1,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175,242
2,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744,114
3,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499,110
4,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000,107
...,...,...,...,...,...,...,...,...,...
815,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN,12039
816,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN,9834
817,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN,5022
818,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN,6172
819,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN,13358

In [33]:
df['총사망자'].shift().values

array([   nan,    54.,    60.,    66.,    67.,    72.,    75.,    75.,
          81.,    84.,    91.,    94.,   102.,   104.,   111.,   120.,
         126.,   131.,   139.,   144.,   152.,   158.,   162.,   165.,
         169.,   174.,   177.,   183.,   186.,   192.,   200.,   204.,
         208.,   211.,   214.,   217.,   222.,   225.,   229.,   230.,
         232.,   234.,   236.,   237.,   238.,   240.,   240.,   240.,
         242.,   243.,   244.,   246.,   247.,   248.,   250.,   250.,
         252.,   254.,   255.,   256.,   256.,   256.,   256.,   256.,
         258.,   259.,   260.,   262.,   262.,   263.,   263.,   263.,
         264.,   264.,   266.,   266.,   267.,   269.,   269.,   269.,
         269.,   269.,   270.,   271.,   272.,   273.,   273.,   273.,
         273.,   273.,   273.,   274.,   276.,   276.,   277.,   277.,
         277.,   277.,   278.,   279.,   280.,   280.,   280.,   280.,
         280.,   281.,   281.,   282.,   282.,   282.,   282.,   282.,
         282.,   282.,   282.,   282.,   283.,   283.,   284.,   285.,
         285.,   287.,   288.,   288.,   289.,   289.,   289.,   289.,
         291.,   293.,   294.,   295.,   296.,   296.,   297.,   297.,
         298.,   298.,   298.,   299.,   300.,   300.,   300.,   301.,
         301.,   301.,   301.,   301.,   302.,   302.,   303.,   304.,
         305.,   305.,   305.,   305.,   305.,   305.,   305.,   305.,
         305.,   306.,   306.,   307.,   309.,   309.,   309.,   309.,
         310.,   312.,   313.,   316.,   321.,   323.,   324.,   324.,
         326.,   329.,   331.,   333.,   334.,   336.,   341.,   344.,
         346.,   350.,   355.,   358.,   363.,   367.,   367.,   372.,
         377.,   378.,   383.,   385.,   388.,   388.,   393.,   395.,
         399.,   401.,   406.,   407.,   413.,   415.,   416.,   420.,
         421.,   422.,   422.,   425.,   427.,   428.,   430.,   432.,
         433.,   434.,   438.,   439.,   441.,   443.,   444.,   444.,
         447.,   450.,   453.,   455.,   457.,   457.,   457.,   460.,
         461.,   462.,   463.,   464.,   466.,   468.,   472.,   474.,
         475.,   476.,   477.,   478.,   480.,   485.,   487.,   487.,
         488.,   492.,   493.,   494.,   494.,   496.,   498.,   501.,
         503.,   505.,   509.,   510.,   513.,   515.,   516.,   522.,
         523.,   526.,   526.,   526.,   529.,   536.,   540.,   545.,
         549.,   552.,   556.,   564.,   572.,   578.,   580.,   587.,
         600.,   612.,   634.,   645.,   659.,   674.,   698.,   722.,
         739.,   756.,   773.,   793.,   808.,   819.,   859.,   879.,
         900.,   917.,   942.,   962.,   981.,  1007.,  1027.,  1046.,
        1081.,  1100.,  1125.,  1140.,  1165.,  1185.,  1195.,  1217.,
        1236.,  1249.,  1264.,  1283.,  1300.,  1316.,  1328.,  1337.,
        1349.,  1360.,  1371.,  1378.,  1386.,  1399.,  1414.,  1420.,
        1425.,  1435.,  1441.,  1448.,  1459.,  1464.,  1471.,  1474.,
        1482.,  1486.,  1496.,  1507.,  1514.,  1522.,  1527.,  1534.,
        1538.,  1544.,  1550.,  1553.,  1557.,  1562.,  1573.,  1576.,
        1581.,  1585.,  1595.,  1603.,  1605.,  1606.,  1612.,  1619.,
        1627.,  1632.,  1634.,  1642.,  1645.,  1648.,  1652.,  1662.,
        1667.,  1669.,  1675.,  1678.,  1686.,  1688.,  1690.,  1693.,
        1696.,  1697.,  1704.,  1707.,  1709.,  1716.,  1721.,  1722.,
        1726.,  1729.,  1731.,  1735.,  1737.,  1740.,  1744.,  1748.,
        1752.,  1756.,  1758.,  1764.,  1765.,  1768.,  1770.,  1775.,
        1782.,  1788.,  1790.,  1794.,  1797.,  1801.,  1802.,  1806.,
        1808.,  1811.,  1812.,  1813.,  1817.,  1820.,  1821.,  1825.,
        1828.,  1831.,  1833.,  1834.,  1840.,  1847.,  1851.,  1860.,
        1865.,  1874.,  1875.,  1879.,  1884.,  1891.,  1893.,  1896.,
        1900.,  1903.,  1904.,  1912.,  1916.,  1922.,  1926.,  1931.,
        1934.,  1938.,  1940.,  1943.,  1946.,  1951.,  1959.,  1957.,
        1963.,  1965.,  1968.,  1969.,  1971.,  1973.,  1974.,  1975.,
        1977.,  1979.,  1981.,  1982.,  1985.,  1988.,  1992.,  1993.,
        1994.,  1996.,  1997.,  2002.,  2004.,  2006.,  2007.,  2008.,
        2009.,  2012.,  2013.,  2015.,  2017.,  2018.,  2021.,  2024.,
        2025.,  2026.,  2028.,  2032.,  2033.,  2034.,  2036.,  2038.,
        2043.,  2044.,  2046.,  2048.,  2050.,  2051.,  2055.,  2057.,
        2058.,  2059.,  2060.,  2063.,  2066.,  2068.,  2073.,  2077.,
        2079.,  2083.,  2085.,  2089.,  2095.,  2098.,  2099.,  2104.,
        2106.,  2109.,  2113.,  2116.,  2121.,  2125.,  2134.,  2135.,
        2138.,  2144.,  2148.,  2156.,  2167.,  2173.,  2178.,  2191.,
        2197.,  2202.,  2215.,  2222.,  2228.,  2237.,  2257.,  2265.,
        2276.,  2279.,  2284.,  2285.,  2292.,  2303.,  2308.,  2315.,
        2321.,  2327.,  2330.,  2334.,  2343.,  2348.,  2358.,  2359.,
        2360.,  2367.,  2380.,  2386.,  2389.,  2394.,  2403.,  2409.,
        2413.,  2419.,  2427.,  2434.,  2441.,  2450.,  2456.,  2464.,
        2474.,  2481.,  2497.,  2504.,  2507.,  2513.,  2524.,  2536.,
        2544.,  2554.,  2560.,  2575.,  2583.,  2594.,  2605.,  2618.,
        2626.,  2644.,  2660.,  2668.,  2689.,  2698.,  2709.,  2725.,
        2745.,  2766.,  2773.,  2788.,  2797.,  2808.,  2817.,  2830.,
        2849.,  2858.,  2874.,  2892.,  2916.,  2936.,  2956.,  2967.,
        2980.,  2998.,  3012.,  3033.,  3051.,  3083.,  3103.,  3115.,
        3137.,  3158.,  3187.,  3215.,  3244.,  3274.,  3298.,  3328.,
        3362.,  3401.,  3440.,  3492.,  3548.,  3580.,  3624.,  3658.,
        3705.,  3739.,  3809.,  3852.,  3893.,  3957.,  4020.,  4077.,
        4130.,  4210.,  4252.,  4292.,  4386.,  4456.,  4518.,  4591.,
        4644.,  4722.,  4776.,  4828.,  4906.,  5015.,  5071.,  5176.,
        5245.,  5300.,  5346.,  5382.,  5455.,  5563.,  5625.,  5694.,
        5730.,  5781.,  5838.,  5887.,  5932.,  5986.,  6037.,  6071.,
        6114.,  6166.,  6210.,  6259.,  6281.,  6310.,  6333.,  6378.,
        6452.,  6480.,  6501.,  6529.,  6540.,  6565.,  6588.,  6620.,
        6654.,  6678.,  6712.,  6732.,  6755.,  6772.,  6787.,  6812.,
        6836.,  6858.,  6873.,  6886.,  6922.,  6943.,  6963.,  7012.,
        7045.,  7081.,  7102.,  7163.,  7202.,  7238.,  7283.,  7354.,
        7405.,  7450.,  7508.,  7607.,  7689.,  7783.,  7895.,  7944.,
        8058.,  8170.,  8266.,  8394.,  8580.,  8796.,  8957.,  9096.,
        9282.,  9440.,  9646.,  9875., 10144., 10395., 10595., 10888.,
       11052., 11481., 11782., 12101., 12428., 12757., 13141., 13432.,
       13901., 14294., 14617., 14899., 15186., 15423., 15855., 16230.,
       16590., 16929., 17235., 17453., 17662., 18033., 18381., 18754.,
       19092., 19421., 19679., 19850., 20034., 20352., 20616., 20889.,
       21092., 21224., 21354., 21520., 21667., 21873., 22024., 22133.,
       22243., 22325., 22466., 22588., 22724., 22794., 22875., 22958.,
       23007., 23079., 23158., 23206., 23289., 23360., 23400., 23462.,
       23491., 23554., 23606., 23661., 23709., 23744., 23771., 23802.,
       23842., 23885., 23911., 23965., 23987., 24006., 24029., 24063.,
       24103., 24139., 24158., 24167., 24176., 24197., 24212., 24229.,
       24238., 24258., 24279., 24299.])

In [34]:
df['일일사망자'] = df['총사망자'] - df['총사망자'].shift()

In [35]:
df

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일확진자,일일사망자
0,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308,0,NaN
1,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175,242,6.0
2,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744,114,6.0
3,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499,110,1.0
4,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000,107,5.0
...,...,...,...,...,...,...,...,...,...,...
815,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN,12039,9.0
816,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN,9834,20.0
817,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN,5022,21.0
818,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN,6172,20.0
819,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,NaN,NaN,NaN,13358,6.0

In [36]:
# 특정 시리즈 안에서 차이를 구하는 함수
# diff(n) -> n : 인덱스의 수
df['총사망자'].diff()

0       NaN
1       6.0
2       6.0
3       1.0
4       5.0
       ...
815     9.0
816    20.0
817    21.0
818    20.0
819     6.0
Name: 총사망자, Length: 820, dtype: float64

In [38]:
# 일일사망자, 일일확진자 데이터는 범위가 0보다 크거나 같은 데이터여야 한다.
# 비교 연산자를 이용하여 해당 데이터들을 확인
df['일일사망자'].fillna(0, inplace=True)

C:\Users\johnh\AppData\Local\Temp\ipykernel_16932\1204490329.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['일일사망자'].fillna(0, inplace=True)

In [41]:
flag = df['일일사망자'] >= 0

In [ ]:
df.loc[flag,]

In [43]:
flag = df['일일확진자'] < 0
df.loc[flag, ]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일확진자,일일사망자
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,9747612.0,1.454166,-430,-2.0

In [47]:
# # 일일확진자, 일일사망자 두개의 컬럼을 모두 선택해서 비교
# flag = df[['일일확진자', '일일사망자']] < 0
# # 인덱스의 조건식에 1차원 데이터형이 아닌 2차원 데이터가 들어가면 에러 발생
# df.loc[flag,]

In [51]:
flag = (df[['일일확진자','일일사망자']]<0).any(axis=1)

In [52]:
df.loc[flag,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일확진자,일일사망자
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,9747612.0,1.454166,-430,-2.0

In [53]:
# 446번 인덱스에서 문제가 보인다.
# 444번 인덱스부터 448번 인덱스까지 데이터 확인
df.loc[444:448, ]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일확진자,일일사망자
444,2021-05-29 00:00:00.000,1951,139427,20210529,00:00,2021-10-07 10:30:51.51,9733588.0,1.450884,533,5.0
445,2021-05-30 00:00:00.0,1959,140337,20210531,00:00,2021-10-14 13:48:56.821,9761156.0,1.456805,910,8.0
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,9747612.0,1.454166,-430,-2.0
447,2021-06-01 00:00:00.000,1963,140796,20210601,00:00,2021-10-07 10:30:51.51,9798400.0,1.455890,889,6.0
448,2021-06-02 00:00:00.000,1965,141473,20210602,00:00,2021-10-07 10:30:51.51,9834348.0,1.457668,677,2.0

1. 등록일시를 기준으로 오름차순 정렬
2. 인덱스를 초기화하고 기존의 인덱스는 제거
3. '일일확진자','일일확진자' 컬럼을 제거
4. '일일확진자' 컬럼은 shift()함수를 이용해서 생성
5. '일일사망자' 컬럼은 diff()함수를 이용해서 생성
5. '일일확진자', '일일사망자' 컬럼의 데이터에서 음수가 존재하는지 확인

In [ ]:
# 인덱스를 초기화하고(reset.index()) 기존의 인덱스를 제거
df.reset_index(drop=True)

In [ ]:
df.sort_values('등록일시')

In [ ]:
df.drop(columns=['일일확진자','일일사망자'], inplace=True)
# df.drop(['일일사망자', '일일사망자'], axis = 'columns', inplace = True) 도 가능

In [80]:
df['일일사망자']=df['총사망자'].diff()

In [90]:
df.fillna(0)

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일사망자,일일확진자
0,2020-03-10 00:00:00.000,54,7513,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308,0.0,0.0
1,2020-03-11 00:00:00.000,60,7755,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175,6.0,242.0
2,2020-03-12 00:00:00.000,66,7869,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744,6.0,114.0
3,2020-03-13 00:00:00.000,67,7979,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499,1.0,110.0
4,2020-03-14 00:00:00.000,72,8086,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000,5.0,107.0
...,...,...,...,...,...,...,...,...,...,...
815,2022-06-04 08:56:49.219,24238,18153814,20220604,00:00,2022-06-08 09:11:26.303,0.0,0.000000,9.0,12039.0
816,2022-06-05 08:53:19.426,24258,18163648,20220605,00:00,2022-06-08 09:11:04.758,0.0,0.000000,20.0,9834.0
817,2022-06-06 09:00:06.734,24279,18168670,20220606,00:00,2022-06-08 09:10:50.441,0.0,0.000000,21.0,5022.0
818,2022-06-07 09:09:00.897,24299,18174842,20220607,00:00,2022-06-08 09:10:36.846,0.0,0.000000,20.0,6172.0
819,2022-06-08 09:09:05.982,24305,18188200,20220608,00:00,0,0.0,0.000000,6.0,13358.0

In [93]:
df['일일확진자'] = (df['총확진자'] - df['총확진자'].shift()).fillna(0)

In [94]:
df.loc[444:448]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일사망자,일일확진자
444,2021-05-29 00:00:00.000,1951,139427,20210529,00:00,2021-10-07 10:30:51.51,9733588.0,1.450884,5.0,533.0
445,2021-05-30 00:00:00.0,1959,140337,20210531,00:00,2021-10-14 13:48:56.821,9761156.0,1.456805,8.0,910.0
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,9747612.0,1.454166,-2.0,-430.0
447,2021-06-01 00:00:00.000,1963,140796,20210601,00:00,2021-10-07 10:30:51.51,9798400.0,1.455890,6.0,889.0
448,2021-06-02 00:00:00.000,1965,141473,20210602,00:00,2021-10-07 10:30:51.51,9834348.0,1.457668,2.0,677.0

In [100]:
flag = (df[['일일사망자','일일확진자']] < 0).any(axis=1)
df.loc[flag,]

,등록일시,총사망자,총확진자,기준일,기준시간,수정일시,누적의심자,누적확진율,일일사망자,일일확진자
446,2021-05-30 00:00:00.000,1957,139907,20210530,00:00,2021-10-07 10:30:51.51,9747612.0,1.454166,-2.0,-430.0

In [101]:
flag.sum()

np.int64(1)

In [91]:
df[['일일사망자','일일확진자']].any()

일일사망자    True
일일확진자    True
dtype: bool

In [92]:
df[['일일사망자','일일확진자']].sum()

일일사망자       24251.0
일일확진자    18180687.0
dtype: float64